version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secureblog_backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - SESSION_SECRET=secureblog_session_secret_key_tp1_2026
    volumes:
      - ./backend/data:/app/data
      - ./backend/.env:/app/.env
      - ./backend/src:/app/src
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secureblog_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
